/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as FreeLinkInBioRouteImport } from './routes/free-link-in-bio'
import { Route as InstagramBioLinkRouteImport } from './routes/instagram-bio-link'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LinkInBioRouteImport } from './routes/link-in-bio'
import { Route as LinktreeAlternativeRouteImport } from './routes/linktree-alternative'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedArenaRouteImport } from './routes/_authenticated/arena'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmbedRouteImport } from './routes/_authenticated/embed'
import { Route as AuthenticatedPrivateRouteImport } from './routes/_authenticated/private'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as EmbedUsernameRouteImport } from './routes/embed/$username'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicEmbedClickRouteImport } from './routes/api/public/embed-click'
import { Route as ApiPublicEmbedTrackRouteImport } from './routes/api/public/embed-track'
import { Route as ApiPublicProjectEventRouteImport } from './routes/api/public/project-event'
import { Route as ApiPublicAvatarSplatRouteImport } from './routes/api/public/avatar/$'
import { Route as ApiPublicProjectCoverSplatRouteImport } from './routes/api/public/project-cover/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeLinkInBioRoute = FreeLinkInBioRouteImport.update({
  id: '/free-link-in-bio',
  path: '/free-link-in-bio',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramBioLinkRoute = InstagramBioLinkRouteImport.update({
  id: '/instagram-bio-link',
  path: '/instagram-bio-link',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkInBioRoute = LinkInBioRouteImport.update({
  id: '/link-in-bio',
  path: '/link-in-bio',
  getParentRoute: () => rootRouteImport,
} as any)
const LinktreeAlternativeRoute = LinktreeAlternativeRouteImport.update({
  id: '/linktree-alternative',
  path: '/linktree-alternative',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArenaRoute = AuthenticatedArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmbedRoute = AuthenticatedEmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrivateRoute = AuthenticatedPrivateRouteImport.update({
  id: '/private',
  path: '/private',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EmbedUsernameRoute = EmbedUsernameRouteImport.update({
  id: '/embed/$username',
  path: '/embed/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEmbedClickRoute = ApiPublicEmbedClickRouteImport.update({
  id: '/api/public/embed-click',
  path: '/api/public/embed-click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmbedTrackRoute = ApiPublicEmbedTrackRouteImport.update({
  id: '/api/public/embed-track',
  path: '/api/public/embed-track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProjectEventRoute = ApiPublicProjectEventRouteImport.update({
  id: '/api/public/project-event',
  path: '/api/public/project-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvatarSplatRoute = ApiPublicAvatarSplatRouteImport.update({
  id: '/api/public/avatar/$',
  path: '/api/public/avatar/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProjectCoverSplatRoute =
  ApiPublicProjectCoverSplatRouteImport.update({
    id: '/api/public/project-cover/$',
    path: '/api/public/project-cover/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/developers': typeof DevelopersRoute
  '/examples': typeof ExamplesRoute
  '/free-link-in-bio': typeof FreeLinkInBioRoute
  '/instagram-bio-link': typeof InstagramBioLinkRoute
  '/leaderboard': typeof LeaderboardRoute
  '/link-in-bio': typeof LinkInBioRoute
  '/linktree-alternative': typeof LinktreeAlternativeRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/arena': typeof AuthenticatedArenaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/embed': typeof AuthenticatedEmbedRoute
  '/private': typeof AuthenticatedPrivateRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/embed/$username': typeof EmbedUsernameRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/embed-click': typeof ApiPublicEmbedClickRoute
  '/api/public/embed-track': typeof ApiPublicEmbedTrackRoute
  '/api/public/project-event': typeof ApiPublicProjectEventRoute
  '/api/public/avatar/$': typeof ApiPublicAvatarSplatRoute
  '/api/public/project-cover/$': typeof ApiPublicProjectCoverSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/developers': typeof DevelopersRoute
  '/examples': typeof ExamplesRoute
  '/free-link-in-bio': typeof FreeLinkInBioRoute
  '/instagram-bio-link': typeof InstagramBioLinkRoute
  '/leaderboard': typeof LeaderboardRoute
  '/link-in-bio': typeof LinkInBioRoute
  '/linktree-alternative': typeof LinktreeAlternativeRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/arena': typeof AuthenticatedArenaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/embed': typeof AuthenticatedEmbedRoute
  '/private': typeof AuthenticatedPrivateRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/embed/$username': typeof EmbedUsernameRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/embed-click': typeof ApiPublicEmbedClickRoute
  '/api/public/embed-track': typeof ApiPublicEmbedTrackRoute
  '/api/public/project-event': typeof ApiPublicProjectEventRoute
  '/api/public/avatar/$': typeof ApiPublicAvatarSplatRoute
  '/api/public/project-cover/$': typeof ApiPublicProjectCoverSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$username': typeof UsernameRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/developers': typeof DevelopersRoute
  '/examples': typeof ExamplesRoute
  '/free-link-in-bio': typeof FreeLinkInBioRoute
  '/instagram-bio-link': typeof InstagramBioLinkRoute
  '/leaderboard': typeof LeaderboardRoute
  '/link-in-bio': typeof LinkInBioRoute
  '/linktree-alternative': typeof LinktreeAlternativeRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/arena': typeof AuthenticatedArenaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/embed': typeof AuthenticatedEmbedRoute
  '/_authenticated/private': typeof AuthenticatedPrivateRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/embed/$username': typeof EmbedUsernameRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/embed-click': typeof ApiPublicEmbedClickRoute
  '/api/public/embed-track': typeof ApiPublicEmbedTrackRoute
  '/api/public/project-event': typeof ApiPublicProjectEventRoute
  '/api/public/avatar/$': typeof ApiPublicAvatarSplatRoute
  '/api/public/project-cover/$': typeof ApiPublicProjectCoverSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/auth'
    | '/connect'
    | '/developers'
    | '/examples'
    | '/free-link-in-bio'
    | '/instagram-bio-link'
    | '/leaderboard'
    | '/link-in-bio'
    | '/linktree-alternative'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/analytics'
    | '/arena'
    | '/dashboard'
    | '/embed'
    | '/private'
    | '/settings'
    | '/embed/$username'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/embed-click'
    | '/api/public/embed-track'
    | '/api/public/project-event'
    | '/api/public/avatar/$'
    | '/api/public/project-cover/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/auth'
    | '/connect'
    | '/developers'
    | '/examples'
    | '/free-link-in-bio'
    | '/instagram-bio-link'
    | '/leaderboard'
    | '/link-in-bio'
    | '/linktree-alternative'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/analytics'
    | '/arena'
    | '/dashboard'
    | '/embed'
    | '/private'
    | '/settings'
    | '/embed/$username'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/embed-click'
    | '/api/public/embed-track'
    | '/api/public/project-event'
    | '/api/public/avatar/$'
    | '/api/public/project-cover/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$username'
    | '/auth'
    | '/connect'
    | '/developers'
    | '/examples'
    | '/free-link-in-bio'
    | '/instagram-bio-link'
    | '/leaderboard'
    | '/link-in-bio'
    | '/linktree-alternative'
    | '/mcp'
    | '/reset-password'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/analytics'
    | '/_authenticated/arena'
    | '/_authenticated/dashboard'
    | '/_authenticated/embed'
    | '/_authenticated/private'
    | '/_authenticated/settings'
    | '/embed/$username'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/embed-click'
    | '/api/public/embed-track'
    | '/api/public/project-event'
    | '/api/public/avatar/$'
    | '/api/public/project-cover/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  UsernameRoute: typeof UsernameRoute
  AuthRoute: typeof AuthRoute
  ConnectRoute: typeof ConnectRoute
  DevelopersRoute: typeof DevelopersRoute
  ExamplesRoute: typeof ExamplesRoute
  FreeLinkInBioRoute: typeof FreeLinkInBioRoute
  InstagramBioLinkRoute: typeof InstagramBioLinkRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LinkInBioRoute: typeof LinkInBioRoute
  LinktreeAlternativeRoute: typeof LinktreeAlternativeRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  EmbedUsernameRoute: typeof EmbedUsernameRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicEmbedClickRoute: typeof ApiPublicEmbedClickRoute
  ApiPublicEmbedTrackRoute: typeof ApiPublicEmbedTrackRoute
  ApiPublicProjectEventRoute: typeof ApiPublicProjectEventRoute
  ApiPublicAvatarSplatRoute: typeof ApiPublicAvatarSplatRoute
  ApiPublicProjectCoverSplatRoute: typeof ApiPublicProjectCoverSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-link-in-bio': {
      id: '/free-link-in-bio'
      path: '/free-link-in-bio'
      fullPath: '/free-link-in-bio'
      preLoaderRoute: typeof FreeLinkInBioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram-bio-link': {
      id: '/instagram-bio-link'
      path: '/instagram-bio-link'
      fullPath: '/instagram-bio-link'
      preLoaderRoute: typeof InstagramBioLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link-in-bio': {
      id: '/link-in-bio'
      path: '/link-in-bio'
      fullPath: '/link-in-bio'
      preLoaderRoute: typeof LinkInBioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linktree-alternative': {
      id: '/linktree-alternative'
      path: '/linktree-alternative'
      fullPath: '/linktree-alternative'
      preLoaderRoute: typeof LinktreeAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/arena': {
      id: '/_authenticated/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof AuthenticatedArenaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/embed': {
      id: '/_authenticated/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof AuthenticatedEmbedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/private': {
      id: '/_authenticated/private'
      path: '/private'
      fullPath: '/private'
      preLoaderRoute: typeof AuthenticatedPrivateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/embed/$username': {
      id: '/embed/$username'
      path: '/embed/$username'
      fullPath: '/embed/$username'
      preLoaderRoute: typeof EmbedUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/embed-click': {
      id: '/api/public/embed-click'
      path: '/api/public/embed-click'
      fullPath: '/api/public/embed-click'
      preLoaderRoute: typeof ApiPublicEmbedClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/embed-track': {
      id: '/api/public/embed-track'
      path: '/api/public/embed-track'
      fullPath: '/api/public/embed-track'
      preLoaderRoute: typeof ApiPublicEmbedTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/project-event': {
      id: '/api/public/project-event'
      path: '/api/public/project-event'
      fullPath: '/api/public/project-event'
      preLoaderRoute: typeof ApiPublicProjectEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/avatar/$': {
      id: '/api/public/avatar/$'
      path: '/api/public/avatar/$'
      fullPath: '/api/public/avatar/$'
      preLoaderRoute: typeof ApiPublicAvatarSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/project-cover/$': {
      id: '/api/public/project-cover/$'
      path: '/api/public/project-cover/$'
      fullPath: '/api/public/project-cover/$'
      preLoaderRoute: typeof ApiPublicProjectCoverSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedArenaRoute: typeof AuthenticatedArenaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmbedRoute: typeof AuthenticatedEmbedRoute
  AuthenticatedPrivateRoute: typeof AuthenticatedPrivateRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedArenaRoute: AuthenticatedArenaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmbedRoute: AuthenticatedEmbedRoute,
  AuthenticatedPrivateRoute: AuthenticatedPrivateRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  UsernameRoute: UsernameRoute,
  AuthRoute: AuthRoute,
  ConnectRoute: ConnectRoute,
  DevelopersRoute: DevelopersRoute,
  ExamplesRoute: ExamplesRoute,
  FreeLinkInBioRoute: FreeLinkInBioRoute,
  InstagramBioLinkRoute: InstagramBioLinkRoute,
  LeaderboardRoute: LeaderboardRoute,
  LinkInBioRoute: LinkInBioRoute,
  LinktreeAlternativeRoute: LinktreeAlternativeRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  EmbedUsernameRoute: EmbedUsernameRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicEmbedClickRoute: ApiPublicEmbedClickRoute,
  ApiPublicEmbedTrackRoute: ApiPublicEmbedTrackRoute,
  ApiPublicProjectEventRoute: ApiPublicProjectEventRoute,
  ApiPublicAvatarSplatRoute: ApiPublicAvatarSplatRoute,
  ApiPublicProjectCoverSplatRoute: ApiPublicProjectCoverSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
